/*
 * Copyright (C) 2025 Intel Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "TerminalDescriptorAutogen.h"

TerminalDescriptor SW_ISYSTerminalDesc[] = {
    {
        SW_ISYS_TERMINAL_LOAD_ALGO_FRAME_IN,
        TERMINAL_TYPE_LOAD,
        "TERMINAL_LOAD_ALGO_FRAME_IN",
        PAC_BUFFER_TYPE_PARAM_IN,
        TERMINAL_BUFFER_TYPE_METADATA,
        TERMINAL_DIR_IN,
        0,
    },
    {
        SW_ISYS_TERMINAL_LOAD_ALGO_STREAM_IN,
        TERMINAL_TYPE_LOAD,
        "TERMINAL_LOAD_ALGO_STREAM_IN",
        PAC_BUFFER_TYPE_PROGRAM,
        TERMINAL_BUFFER_TYPE_METADATA,
        TERMINAL_DIR_IN,
        0,
    },
    {
        SW_ISYS_TERMINAL_CONNECT_INPUT_UPIPE, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_INPUT_UPIPE",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_IN,
        36280,  // crop_bpp_adjust_1_0
    },
    {
        SW_ISYS_TERMINAL_CONNECT_OUTPUT_CV, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_OUTPUT_CV",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        26150,  // isys_drainer_1_0
    },
    {
        SW_ISYS_TERMINAL_CONNECT_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_INPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_IN,
        11470,  // is_odr_a
    },
    {
        SW_ISYS_TERMINAL_CONNECT_OUTPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_OUTPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        11470,  // is_odr_a
    },
    {
        SW_ISYS_TERMINAL_CONNECT_INPUT_PDAF, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_INPUT_PDAF",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_IN,
        55449,  // is_odr_b
    },
    {
        SW_ISYS_TERMINAL_CONNECT_OUTPUT_PDAF, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_OUTPUT_PDAF",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        55449,  // is_odr_b
    },
    {
        SW_ISYS_TERMINAL_CONNECT_INPUT_DOL_LONG, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_INPUT_DOL_LONG", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_IN,
        50407,  // is_odr_c
    },
    {
        SW_ISYS_TERMINAL_CONNECT_OUTPUT_DOL_LONG, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_OUTPUT_DOL_LONG", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_OUT,
        50407,  // is_odr_c
    },
};

TerminalDescriptor LBFFTerminalDesc[] = {
    {
        LBFF_TERMINAL_LOAD_ALGO_CACHED,
        TERMINAL_TYPE_LOAD,
        "TERMINAL_LOAD_ALGO_CACHED",
        PAC_BUFFER_TYPE_PARAM_IN,
        TERMINAL_BUFFER_TYPE_METADATA,
        TERMINAL_DIR_IN,
        0,
    },
    {
        LBFF_TERMINAL_LOAD_ALGO_FRAG_SEQ,
        TERMINAL_TYPE_LOAD,
        "TERMINAL_LOAD_ALGO_FRAG_SEQ",
        PAC_BUFFER_TYPE_PROGRAM,
        TERMINAL_BUFFER_TYPE_METADATA,
        TERMINAL_DIR_IN,
        0,
    },
    {
        LBFF_TERMINAL_LOAD_SYSTEM,
        TERMINAL_TYPE_LOAD,
        "TERMINAL_LOAD_SYSTEM",
        PAC_BUFFER_TYPE_SYS_FRAG_SEQUENCER,
        TERMINAL_BUFFER_TYPE_METADATA,
        TERMINAL_DIR_IN,
        0,
    },
    {
        LBFF_TERMINAL_LOAD_SR_FRAME_IN,
        TERMINAL_TYPE_LOAD,
        "TERMINAL_LOAD_SR_FRAME_IN",
        PAC_BUFFER_TYPE_SR_FRAME_IN,
        TERMINAL_BUFFER_TYPE_METADATA,
        TERMINAL_DIR_IN_OUT,
        0,
    },
    {
        LBFF_TERMINAL_CONNECT_MAIN_DATA_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_MAIN_DATA_INPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_IN,
        52446,  // ifd_pipe_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_DOL_LONG_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_DOL_LONG_INPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_IN,
        24678,  // ifd_pipe_long_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_DOL_SHORT_SMTH_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_DOL_SHORT_SMTH_INPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_IN,
        4386,  // ifd_pipe_short_smth_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_LSC_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_LSC_INPUT",
        PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        29313,  // ifd_lsc_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_PDAF_DATA_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_PDAF_DATA_INPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_IN,
        22427,  // ifd_pdaf_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_AE_OUTPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_AE_OUTPUT",
        PAC_BUFFER_TYPE_SPATIAL_OUT, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        62556,  // odr_ae_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_AF_STD_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_AF_STD_OUTPUT", PAC_BUFFER_TYPE_SPATIAL_OUT,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        59136,  // odr_af_std_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_AWB_STD_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_AWB_STD_OUTPUT", PAC_BUFFER_TYPE_SPATIAL_OUT,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        38544,  // odr_awb_std_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_AWB_SAT_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_AWB_SAT_OUTPUT", PAC_BUFFER_TYPE_SPATIAL_OUT,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        1248,  // odr_awb_sat_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_PDAF_OUTPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_PDAF_OUTPUT",
        PAC_BUFFER_TYPE_SPATIAL_OUT, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        26892,  // odr_pdaf_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_IR_OUTPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_IR_OUTPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        60297,  // odr_ir_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BURST_ISP_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_BURST_ISP_OUTPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_OUT,
        0,  // No graphs found
    },
    {
        LBFF_TERMINAL_CONNECT_BNLM_OUTPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_BNLM_OUTPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        53535,  // odr_bnlm_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_GMV_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_GMV_INPUT",
        PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        51073,  // ifd_gmv_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_AWB_SVE_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_AWB_SVE_OUTPUT", PAC_BUFFER_TYPE_SPATIAL_OUT,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        53430,  // odr_awb_sve_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_DPC_PDAF_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_DPC_PDAF_OUTPUT", PAC_BUFFER_TYPE_SPATIAL_OUT,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        54812,  // odr_dpc_pdaf_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_GMV_MATCH_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_GMV_MATCH_OUTPUT", PAC_BUFFER_TYPE_SPATIAL_OUT,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        41148,  // odr_gmv_match_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_GMV_FEATURE_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_GMV_FEATURE_OUTPUT", PAC_BUFFER_TYPE_SPATIAL_OUT,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        7416,  // odr_gmv_feature_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BC_YUV_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_BC_YUV_INPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_IN,
        7357,  // ifd_tnr_sp_bc_yuv4nm1_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BC_RS_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_BC_RS_INPUT",
        PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        62054,  // ifd_tnr_sp_bc_rs4nm1_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BC_OUTPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_BC_OUTPUT",
        PAC_BUFFER_TYPE_SPATIAL_OUT, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        63731,  // odr_tnr_sp_bc_rs4n_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BLEND_YUV_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_BLEND_YUV_INPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_IN,
        16295,  // ifd_tnr_fp_blend_yuvnm1_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BLEND_OUTPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_BLEND_OUTPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        5215,  // odr_tnr_fp_yuvn_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_TNR_SCALER_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_TNR_SCALER_OUTPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_OUT,
        65437,  // odr_tnr_scale_fp_yuv4n_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_OFS_MP_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_OFS_MP_OUTPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_OUT,
        16460,  // odr_ofs_mp_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_OFS_DP_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_OFS_DP_OUTPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_OUT,
        37951,  // odr_ofs_dp_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BNLM_SM_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_BNLM_SM_INPUT", PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA,
        TERMINAL_DIR_IN,
        35263,  // ifd_segmap_bnlm_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_XNR_SM_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_XNR_SM_INPUT",
        PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        9241,  // ifd_segmap_xnr_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_ACM_SM_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_ACM_SM_INPUT",
        PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        51914,  // ifd_segmap_acm_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BC_SM_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_BC_SM_INPUT",
        PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        47873,  // ifd_segmap_tnr_bc_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BLEND_SM_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_BLEND_SM_INPUT", PAC_BUFFER_TYPE_SPATIAL_IN,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        14619,  // ifd_segmap_tnr_blend_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_CAS_SM_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_CAS_SM_INPUT",
        PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        20893,  // ifd_segmap_cas_1_4
    },
    {
        LBFF_TERMINAL_CONNECT_BGB_BM_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_BGB_BM_INPUT",
        PAC_BUFFER_TYPE_SPATIAL_IN, TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_IN,
        0,  // No graphs found
    },
    {
        LBFF_TERMINAL_CONNECT_BGB_YUV_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_BGB_YUV_INPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_IN,
        0,  // No graphs found
    },
};

TerminalDescriptor SW_SEGNETTerminalDesc[] = {
    {
        SW_SEGNET_TERMINAL_CONNECT_CV_DATA_INPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_CV_DATA_INPUT", PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA,
        TERMINAL_DIR_IN,
        0,  // sw_segnet
    },
    {
        SW_SEGNET_TERMINAL_CONNECT_CV_DATA_OUTPUT, TERMINAL_TYPE_CONNECT,
        "TERMINAL_CONNECT_CV_DATA_OUTPUT", PAC_BUFFER_TYPE_SPATIAL_OUT,
        TERMINAL_BUFFER_TYPE_METADATA, TERMINAL_DIR_OUT,
        0,  // sw_segnet
    },
};

TerminalDescriptor SW_GDCTerminalDesc[] = {
    {
        SW_GDC_TERMINAL_CONNECT_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_INPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_IN,
        5637,  // gdc7_1
    },
    {
        SW_GDC_TERMINAL_CONNECT_OUTPUT_1, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_OUTPUT_1",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        0,  //
    },
    {
        SW_GDC_TERMINAL_CONNECT_OUTPUT_2, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_OUTPUT_2",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        0,  //
    },
};

TerminalDescriptor SW_SCALERTerminalDesc[] = {
    {
        SW_SCALER_TERMINAL_CONNECT_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_INPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_IN,
        19706,  // sw_scaler
    },
    {
        SW_SCALER_TERMINAL_CONNECT_OUTPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_OUTPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        19706,  // sw_scaler
    },
};

TerminalDescriptor SW_NNTMTerminalDesc[] = {
    {
        SW_NNTM_TERMINAL_CONNECT_INPUT, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_INPUT",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_IN,
        46539,  // nntm_1_0
    },
    {
        SW_NNTM_TERMINAL_CONNECT_OUTPUT_1, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_OUTPUT_1",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        0,  //
    },
    {
        SW_NNTM_TERMINAL_CONNECT_OUTPUT_2, TERMINAL_TYPE_CONNECT, "TERMINAL_CONNECT_OUTPUT_2",
        PAC_BUFFER_TYPE_NONE, TERMINAL_BUFFER_TYPE_DATA, TERMINAL_DIR_OUT,
        0,  //
    },
};

int CountOfSW_ISYSTerminalDesc = sizeof(SW_ISYSTerminalDesc) / sizeof(SW_ISYSTerminalDesc[0]);
int CountOfLBFFTerminalDesc = sizeof(LBFFTerminalDesc) / sizeof(LBFFTerminalDesc[0]);
int CountOfSW_SEGNETTerminalDesc = sizeof(SW_SEGNETTerminalDesc) / sizeof(SW_SEGNETTerminalDesc[0]);
int CountOfSW_GDCTerminalDesc = sizeof(SW_GDCTerminalDesc) / sizeof(SW_GDCTerminalDesc[0]);
int CountOfSW_SCALERTerminalDesc = sizeof(SW_SCALERTerminalDesc) / sizeof(SW_SCALERTerminalDesc[0]);
int CountOfSW_NNTMTerminalDesc = sizeof(SW_NNTMTerminalDesc) / sizeof(SW_NNTMTerminalDesc[0]);
